# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiCalculator(object):
    def setupUi(self, UI_Calculator):
        UI_Calculator.setObjectName("UI_Calculator")
        UI_Calculator.resize(321, 491)
        self.centralwidget = QtWidgets.QWidget(UI_Calculator)
        self.centralwidget.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_negetive = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_negetive.setGeometry(QtCore.QRect(0, 410, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_negetive.setFont(font)
        self.pushButton_negetive.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_negetive.setObjectName("pushButton_negetive")
        self.pushButton_decimal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_decimal.setGeometry(QtCore.QRect(160, 410, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_decimal.setFont(font)
        self.pushButton_decimal.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_decimal.setObjectName("pushButton_decimal")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(80, 410, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_substract = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_substract.setGeometry(QtCore.QRect(240, 250, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_substract.setFont(font)
        self.pushButton_substract.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border:3px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(255, 170, 0);\n"
"background-color: rgb(48, 48, 48);\n"
"}")
        self.pushButton_substract.setObjectName("pushButton_substract")
        self.pushButton_equal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_equal.setGeometry(QtCore.QRect(240, 410, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border:3px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(255, 170, 0);\n"
"background-color: rgb(48, 48, 48);\n"
"}")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_multiply.setGeometry(QtCore.QRect(240, 170, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border:3px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(255, 170, 0);\n"
"background-color: rgb(48, 48, 48);\n"
"}")
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(240, 330, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border:3px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(255, 170, 0);\n"
"background-color: rgb(48, 48, 48);\n"
"}")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_divide = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_divide.setGeometry(QtCore.QRect(240, 90, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border:3px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(255, 170, 0);\n"
"background-color: rgb(48, 48, 48);\n"
"}")
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 330, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 330, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 330, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 250, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 250, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 250, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 170, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 170, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 170, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(0, 90, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_percent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_percent.setGeometry(QtCore.QRect(160, 90, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_percent.setFont(font)
        self.pushButton_percent.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(80, 90, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("QPushButton {\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {\n"
"border:2px solid;\n"
"border-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"color: rgb(48, 48, 48);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 321, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        UI_Calculator.setCentralWidget(self.centralwidget)

        self.retranslateUi(UI_Calculator)
        QtCore.QMetaObject.connectSlotsByName(UI_Calculator)

    def retranslateUi(self, UI_Calculator):
        _translate = QtCore.QCoreApplication.translate
        UI_Calculator.setWindowTitle(_translate("UI_Calculator", "Calculator"))
        self.pushButton_negetive.setText(_translate("UI_Calculator", "+/-"))
        self.pushButton_decimal.setText(_translate("UI_Calculator", "."))
        self.pushButton_0.setText(_translate("UI_Calculator", "0"))
        self.pushButton_substract.setText(_translate("UI_Calculator", "-"))
        self.pushButton_equal.setText(_translate("UI_Calculator", "="))
        self.pushButton_multiply.setText(_translate("UI_Calculator", "X"))
        self.pushButton_add.setText(_translate("UI_Calculator", "+"))
        self.pushButton_divide.setText(_translate("UI_Calculator", "÷"))
        self.pushButton_1.setText(_translate("UI_Calculator", "1"))
        self.pushButton_3.setText(_translate("UI_Calculator", "3"))
        self.pushButton_2.setText(_translate("UI_Calculator", "2"))
        self.pushButton_4.setText(_translate("UI_Calculator", "4"))
        self.pushButton_6.setText(_translate("UI_Calculator", "6"))
        self.pushButton_5.setText(_translate("UI_Calculator", "5"))
        self.pushButton_7.setText(_translate("UI_Calculator", "7"))
        self.pushButton_9.setText(_translate("UI_Calculator", "9"))
        self.pushButton_8.setText(_translate("UI_Calculator", "8"))
        self.pushButton_clear.setText(_translate("UI_Calculator", "AC"))
        self.pushButton_percent.setText(_translate("UI_Calculator", "%"))
        self.pushButton_delete.setText(_translate("UI_Calculator", "DEL"))
        self.label.setText(_translate("UI_Calculator", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UI_Calculator = QtWidgets.QMainWindow()
    ui = UiCalculator()
    ui.setupUi(UI_Calculator)
    UI_Calculator.show()
    sys.exit(app.exec_())
